import { useParams, Link } from 'react-router-dom'
import { Helmet } from 'react-helmet-async'
import Markdown from 'react-markdown'
import { usePublicStory } from '../hooks/usePublicStories'

export default function StoryPage() {
  const { id } = useParams<{ id: string }>()
  const { data: story, isLoading, error } = usePublicStory(id || '')

  if (isLoading) {
    return (
      <div className="page-section text-center text-neutral-500">
        Loading story...
      </div>
    )
  }

  if (error || !story) {
    return (
      <div className="page-section text-center">
        <h1 className="page-title">Story Not Found</h1>
        <p className="text-neutral-500 mb-6">
          This story may have been removed or is not yet published.
        </p>
        <Link
          to="/"
          className="text-brand-700 hover:text-brand-800 font-medium focus-visible:ring-2 focus-visible:ring-brand-500 rounded px-1"
        >
          &larr; Back to home
        </Link>
      </div>
    )
  }

  const displayTitle = story.title || story.sourceTitle
  const hasSourceDate = !!story.sourceDatePublished
  const displayDate = story.datePublished || story.dateCrawled
  const dateStr = new Date(displayDate).toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })
  const sourceDateStr = story.sourceDatePublished
    ? new Date(story.sourceDatePublished).toLocaleDateString('en-US', {
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      })
    : null

  const description = story.summary || displayTitle

  return (
    <>
      <Helmet>
        <title>{displayTitle} - Actually Relevant</title>
        <meta name="description" content={description.slice(0, 160)} />
        <meta property="og:title" content={displayTitle} />
        <meta property="og:description" content={description.slice(0, 200)} />
        <meta property="og:type" content="article" />
        <meta property="og:url" content={`https://actuallyrelevant.news/stories/${story.id}`} />
        <meta property="og:image" content="https://actuallyrelevant.news/images/logo-text-square.jpg" />
        {story.datePublished && (
          <meta property="article:published_time" content={story.datePublished} />
        )}
      </Helmet>

      <article className="page-section">
        <header className="mb-8">
          <h1 className="text-3xl md:text-4xl font-bold mb-4">{displayTitle}</h1>

          <time dateTime={displayDate} className="block text-sm text-neutral-500 mb-3">
            {dateStr}
          </time>

          <div className="text-sm text-neutral-500">
            <Link
              to="/methodology"
              className="text-brand-700 hover:text-brand-800 focus-visible:ring-2 focus-visible:ring-brand-500 rounded px-0.5"
            >
              Generated by AI
            </Link>
            {'. Based on an article by '}
            <a
              href={story.sourceUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-brand-700 hover:text-brand-800 focus-visible:ring-2 focus-visible:ring-brand-500 rounded px-0.5"
            >
              {story.feed.title}
            </a>
            {hasSourceDate && <>, published on {sourceDateStr}</>}
            .
          </div>
        </header>

        {/* Summary */}
        {story.summary && (
          <section className="mb-8">
            <h2 className="section-heading">Summary</h2>
            <div className="prose"><Markdown>{story.summary}</Markdown></div>
          </section>
        )}

        {/* Key quote */}
        {story.quote && (
          <blockquote className="border-l-4 border-brand-300 pl-4 py-2 my-8 italic text-neutral-700">
            "{story.quote}"
          </blockquote>
        )}

        {/* Marketing blurb */}
        {story.marketingBlurb && (
          <section className="mb-8 bg-brand-50 rounded-lg p-6">
            <div className="text-brand-800 font-medium"><Markdown>{story.marketingBlurb}</Markdown></div>
          </section>
        )}

        {/* Relevance analysis */}
        {story.relevanceReasons && (
          <section className="mb-8">
            <h2 className="section-heading">Why This Matters</h2>
            <div className="prose"><Markdown>{story.relevanceReasons}</Markdown></div>
          </section>
        )}

        {story.antifactors && (
          <section className="mb-8">
            <h2 className="section-heading">Caveats</h2>
            <div className="prose"><Markdown>{story.antifactors}</Markdown></div>
          </section>
        )}

        {/* Back link */}
        <div className="border-t border-neutral-200 pt-6 mt-8">
          <Link
            to="/"
            className="text-brand-700 hover:text-brand-800 font-medium focus-visible:ring-2 focus-visible:ring-brand-500 rounded px-1"
          >
            &larr; Back to all stories
          </Link>
        </div>
      </article>
    </>
  )
}
